# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 01:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='evento_data',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dundo_noticias', to=settings.AUTH_USER_MODEL),
        ),
    ]
