# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0002_auto_20170321_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('-criado',)},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='publish',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='criado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
