# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0003_auto_20170321_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='noticia',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='criado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
