# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0004_auto_20170321_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='noticia_texto',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.TextField(max_length=250),
        ),
    ]
