# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0005_auto_20170321_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
    ]
