# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0006_auto_20170326_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, upload_to='noticia/%Y/%m/%d'),
        ),
    ]
