# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0008_auto_20170414_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
