# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0009_noticia_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='pub_date',
        ),
    ]
