# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0010_remove_noticia_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='criado',
            new_name='pub_date',
        ),
    ]
