# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0011_auto_20170415_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, upload_to='noticia/%Y/%m/%d'),
        ),
    ]
