# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0013_noticia_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='website',
            new_name='website_image',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='image',
        ),
    ]
