# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0014_auto_20170523_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='website_image',
            new_name='image_url',
        ),
    ]
