# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0016_auto_20170523_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='pub_date',
        ),
    ]
