# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0017_remove_noticia_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fonte',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
