# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0020_remove_noticia_noticia_fonte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('-publicado',)},
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='publish',
            new_name='publicado',
        ),
    ]
