# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0022_auto_20170523_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('-publish',)},
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='publicado',
            new_name='publish',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='estado',
            new_name='status',
        ),
    ]
