# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0026_noticia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fonte_noticia',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
