# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0027_noticia_fonte_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='categoria',
        ),
    ]
