# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0029_noticia_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='titulo',
            new_name='name',
        ),
    ]
