# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import dundo.models


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0031_auto_20170525_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.TextField(max_length=100, null=True, verbose_name=dundo.models.Categoria),
        ),
    ]
