# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0036_auto_20170525_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fonte_noticia',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
