# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0037_auto_20170525_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fonte_url',
            field=models.URLField(blank=True),
        ),
    ]
