# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0038_noticia_fonte_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
