# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0039_noticia_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='pub_date',
        ),
    ]
