# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0040_remove_noticia_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEmprego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Emprego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dundo.CategoriaEmprego')),
            ],
            options={
                'ordering': ('-criado',),
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('nome',), 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='noticia_texto',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterIndexTogether(
            name='emprego',
            index_together=set([('id', 'slug')]),
        ),
    ]
