# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0041_auto_20170609_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('nome',), 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias-Noticia'},
        ),
        migrations.AlterModelOptions(
            name='categoriaemprego',
            options={'ordering': ('nome',), 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias-Emprego'},
        ),
        migrations.RenameField(
            model_name='emprego',
            old_name='disponivel',
            new_name='disponibilidade',
        ),
    ]
