# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0042_auto_20170609_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprego',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empregos', to='dundo.CategoriaEmprego'),
        ),
    ]
