# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dundo', '0043_auto_20170610_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprego',
            name='icon',
            field=models.TextField(blank=True),
        ),
    ]
